#!/usr/bin/env python
#   
#   Copyright (c) 2012-2014 Jeremy Cartwright. All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions
#   are met:
# 
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#   * Neither the name of Jeremy Cartwright nor the names of his
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  
#    Author: Jeremy Cartwright
#   Contact: jeremy@tcjc8.com
#   Created: Thu Mar 13 21:00:57 CDT 2014
#   almanac: an attempt at something useful in python.
#               1) saves random thoughts with $almanac $entry
#               2) shows the thoughts underneath yet to be made calendar call
#                  during appropriate month.


# ~ :$ echo "Your entry here." > /home/$USER/almanac/`date +%s`.txt

import subprocess
from os import environ

dir = environ['HOME']+'/almanac/'

# Filename is seconds since 70.txt
file = str(subprocess.getoutput('date +%s'))+'.txt'

# Read until EOF. Hard return does it.
text = input()

# The data is stored in chosen directory with timestamp.
with open (dir+file, 'a') as entry: entry.write(text)
